### ISSUE TITLE
Product Items not showing in Sales Grid - Magento 2.4.0

### ISSUE THREAD

**Issue by wajahatbashir** [markshust/magento2-module-ordergrid#11]
Hi,

I just installed this extension in Magento 2.4.0. But data is not showing under Order Item details in Sales Order Grid. Please check screenshot link.

https://imgur.com/8oi97w5

any help to fix this issue ?

**Comment by markshust** [comment]
So sorry that I didn't see this bug report until now! But I'm able to see the items just fine on a vanilla install of M2:

<img width="2166" alt="Screen Shot 2022-08-01 at 3 50 28 PM" src="https://user-images.githubusercontent.com/437029/182233296-3fb5021d-f02c-46a9-8b7a-5a29cd47e62b.png">

From your screenshot, it looks like you have customized (or installed a third-party module that modifies) the order status column, which could be conflicting with this module.
