### ISSUE TITLE
Update order_items field into export-friendly format

### ISSUE THREAD

**Issue by igorsKolcinsMagebit** [markshust/magento2-module-ordergrid#12]
Steps to reproduce:
1. Go to orders grid
2. Check orders and export them into CSV

Expected result:
In CSV file products listed without HTML tags

Actual result:
Products separated with HTML tags

![image](https://user-images.githubusercontent.com/46994993/176901115-2ffaf88d-d092-40fa-a2f3-90c264be3b8c.png)

**Comment by markshust** [comment]
Great suggestion! I'm working on this.

**Comment by markshust** [comment]
Appreciate your patience -- this one was tough to figure out.

All updated in version 1.1.0. The export should now look something like this:

<img width="464" alt="Screen Shot 2022-08-01 at 4 51 02 PM" src="https://user-images.githubusercontent.com/437029/182245161-210d6a66-3ac3-4203-8088-7138ead25f20.png">
