### ISSUE TITLE
Magento Version issue

### ISSUE THREAD

**Issue by surelockrich** [markshust/magento2-module-ordergrid#3]
Hello,

Kindly test your module in Magento 2.3.5-p1
there are some issue in layout, kindly check

Thank You

**Comment by markshust** [comment]
I’ll check this out at my convenience. If you wish to get a fix in sooner, please create a PR and I will gladly accept it.

**Comment by arisdhiamandi** [comment]
Hi,
I made the changes but still some issues persist:
1) You cant Apply filters
2) If you select  one item automatically selects all
3) The pager doesn't work
4) It gives only 1 record found
5) And the search doesn't work correctly

Btw i am using Magento 2.4.

Other than that great work.


Thank you

**Comment by arisdhiamandi** [comment]
@markshust hi can you check the issues?

**Comment by surelockrich** [comment]
Hello Team,

will it work on Magento 2.3.5-p2 ?

Regards,

Ali

**Comment by arisdhiamandi** [comment]
@surelockrich Hi the issues persist on the 2.4.0

Thank you

**Comment by markshust** [comment]
@arisdhiamandi I'm knee-deep in a course right now, then taking a much needed vacation afterwards. I can look at this when I return in mid-January. That said, if anyone else would like to fix this issue I'd gladly take in a PR for it! Cheers -Mark

**Comment by arisdhiamandi** [comment]
Hi @markshust , Do you have any update for the issue at v2.4.0

Best Regards

**Comment by markshust** [comment]
@arisdhiamandi I'm super sorry for the delay. I merged https://github.com/markshust/magento2-module-ordergrid/commit/cfd8a1fb08105938a3b6ad8d84686ddced9401e0 which fixes the filter and style issues. I haven't done a lot of testing but pagination and search appear to be working correctly as well. 

The only issue that seems to persist is the select checkbox selecting all elements instead of just one. I haven't had time to look at that yet.

**Comment by arisdhiamandi** [comment]
@arisdhiamandi Thank you for the update, can you give us any estimation when will be fixed?

Best Regards

**Comment by arisdhiamandi** [comment]
Hi @markshust  , Do you have any update?

Best Regards

**Comment by markshust** [comment]
I don't as I'm not actively working on this. Open to taking a PR in by anyone to fix this.

**Comment by ghost** [comment]
@arisdhiamandi @markshust This should hopefully be fixed in #5

**Comment by markshust** [comment]
@rob-aimes thank you very much Rob, just merged in and tagged as 1.0.7. Can you confirm this fixes everything?

**Comment by rob-aimes** [comment]
@markshust Just tested locally and the issues noted in here do seem to be resolved. See below:

![](https://user-images.githubusercontent.com/29477517/112656403-48332400-8e49-11eb-9608-ffe7b73fe481.png)

**Comment by ghost** [comment]
@markshust Just tested locally, the issues noted in this GitHb issue appear resolved. See below:

![](https://user-images.githubusercontent.com/29477517/112656722-93e5cd80-8e49-11eb-84c5-1284d9cad8c0.png)

**Comment by surelockrich** [comment]
Kindly share the source code and tested version.

Thanks & Regards
Ali
