### ISSUE TITLE
Total records found does not work

### ISSUE THREAD

**Issue by JelleGe** [markshust/magento2-module-ordergrid#7]
We found another issue, the total records found does not work in the order grid. It keeps on "1 records found" and also the pagination does not work, it keeps 1 of 1, even if we have more than 10.000 results.

**Comment by ghost** [comment]
@JelleGe This is fixed in #5

**Comment by markshust** [comment]
Thank you, merged in https://github.com/markshust/magento2-module-ordergrid/pull/5
