### ISSUE TITLE
Order grid filter does not work anymore

### ISSUE THREAD

**Issue by JelleGe** [markshust/magento2-module-ordergrid#8]
Hi,

When your module is enabled, the order grid filter does not work anymore.

Can you please check this?

**Comment by JelleGe** [comment]
As addition, the date filter does not work anymore.

**Comment by JelleGe** [comment]
Hi,

Any update about this issue?

**Comment by ghost** [comment]
@JelleGe Does #9 fix your issue?

**Comment by JelleGe** [comment]
Hi Rob,

Thanks! That indeed solved the issue.

**Comment by JelleGe** [comment]
Thanks! #9 indeed solved the issue!

**Comment by markshust** [comment]
Just merged in #9 and tagged as `1.0.9`. Thanks for the PR (and your patience!). I'm all caught up with PR's across all my projects, so hope things go quicker now. Cheers -Mark
